FROM public.ecr.aws/lambda/python:3.13

COPY requirements.lambda.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.lambda.txt \
    --target ${LAMBDA_TASK_ROOT}

COPY app ${LAMBDA_TASK_ROOT}/app

CMD ["app.s3_event_handler.lambda_handler"]
